# Assignment Of Numpy
Piaic-92094

In [4]:
#Import numpy package as np
import numpy as np

In [6]:
#Null Vector of size 10
x=np.zeros((10))
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#Create arange method which limit 0 t0 99
x=np.arange(0,100)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
#finding Shape / size of list
np.shape(x)

(100,)

In [8]:
#Find the data type 
x.dtype

dtype('int32')

In [10]:
#find the numpy version
np.__version__


'1.18.5'

In [11]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/dell/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:

In [26]:
#Finding dimension
np.ndim(x)

1

In [27]:
#1Find boolean function
x>25

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [12]:
#Create a two dimensional array
import numpy as np
arr=np.arange(20).reshape(4,5)
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
#Create a three dimensional array
arr=np.arange(75).reshape(3,5,5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]]])

In [13]:
#Reverse a vector 

x = np.arange(10)
print("Reverse array:")
x = x[::-1]
print(x)

Reverse array:
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [14]:
#Create a null vector of size 10 but the fifth value which is 1
arr=np.zeros(10)
arr[5]=1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [28]:
#Create a 3x3 identity matrix
arr=np.zeros(9).reshape(3,3)
arr[0,0]=1
arr[1,1]=1
arr[2,2]=1
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [38]:
#Convert the data type of the given array from int to float
arr.dtype
arr.astype('float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [40]:
#Multiply arr1 with arr2
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [41]:
#Make an array by comparing both the arrays provided above
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr1 == arr2

array([[False, False, False],
       [False, False, False]])

In [59]:
#Extract all odd numbers from arr with values(0-9)
arr= np.arange((10))
arr[1::2]


array([1, 3, 5, 7, 9])

In [62]:
#Replace all odd numbers to -1 from previous array
arr[1::2]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [63]:
#Replace the values of indexes 5,6,7 and 8 to 10
arr = np.arange(10)
arr[5:8]=10
arr


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [82]:
#Create a 2d array with 1 on the border and 0 inside
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [85]:
#Replace the value 5 to 12
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [89]:
#Convert all the values of 1st array to 64
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=32
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [120]:
#Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
arr2d=np.arange(9).reshape(1,3,3)
arr2d[0,0]



array([0, 1, 2])

In [145]:
#Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
arr2d=np.arange(9).reshape(1,3,3)
arr2d[:,1:2,1]



array([[4]])

In [146]:
#Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

arr2d=np.arange(9).reshape(1,3,3)
arr2d[:,:2,2]


array([[2, 5]])

In [151]:
ranarr=np.random.rand(10,10)
ranarr
print(np.max(ranarr))
np.min(ranarr)

0.9877118986303766


0.008178007775266227

In [154]:
#Find the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b))


[2 4]


In [3]:
import numpy as np
#Find the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

c=np.where(a==b)
print(c)

(array([1, 3, 5, 7], dtype=int64),)


In [14]:
#Find all the values from array data where the values from array names are not equal to Will

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names!='Will')


[ True  True False  True False  True  True]


In [26]:
#Find all the values from array data where the values from array names are not equal to Will and Joe
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
abc=(names=="Will") | (names=="Joe")
print(abc)

[False  True  True False  True  True  True]


In [34]:
#Difficulty Level Hard
#Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
arr2d=np.arange(1,16).reshape(3,5)
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [35]:
#Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
arr2d=np.arange(16).reshape(2,2,4)
arr2d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [39]:
#Swap axes of the array you created in Question 32
arr2d=np.arange(16).reshape(2,2,4)
np.swapaxes(arr2d,0,2)


array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [52]:
#Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

arr=np.arange(10)
res=np.sqrt(arr)
res
res[res<0.5]=0
res

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [56]:
#Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
arr1=np.random.rand(12)
arr2=np.random.rand(12)
arr=np.maximum(arr1,arr2)
arr

array([0.90660873, 0.6403469 , 0.60131738, 0.38131189, 0.51662627,
       0.98288467, 0.99391718, 0.08817775, 0.90176721, 0.83473476,
       0.0759307 , 0.8162372 ])

In [58]:
#Find the unique names and sort them out!
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [59]:
#From array a remove all items present in array b
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c=np.delete(a,b)
c

C:\Users\admin\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  after removing the cwd from sys.path.


array([1, 2, 3, 4, 5])

In [75]:
#Following is the input NumPy array delete column two and insert following new column in its place.
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = numpy.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [76]:
#Find the dot product of the above two matrix
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z=np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

In [13]:
a=np.random.rand(20)
np.cumsum(a)

array([ 0.21164084,  0.73079825,  1.30976498,  2.18930652,  2.51589867,
        2.87544596,  3.39328439,  3.86671913,  4.49899686,  4.98504761,
        5.34258576,  6.25605987,  7.06672884,  7.60281802,  7.95405237,
        8.23783406,  9.16193042, 10.10061821, 10.28705506, 11.0327243 ])